In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly as py
import plotly.graph_objs as go
import plotly.io as pio
from datetime import datetime
from datetime import timedelta


#py.offline.init_notebook_mode(connected=True)
pio.renderers.default = "notebook"
#pio.renderers

In [2]:
def get_dataframe(signal, file_path, column_names):
    
    def get_sample_time(index, init_time, Ts):
        aux = []
        for i in index:
            aux.append((init_time + timedelta(seconds=Ts*i)).strftime("%H:%M:%S:%f"))

        return aux

    df = pd.read_csv(file_path, names=column_names, header=None)
    timestamp = df.iloc[0, :][0]
    
    if signal in ('acc', 'eda', 'hr', 'temp', 'bvp'):
        initial_time = datetime.utcfromtimestamp(timestamp)
        fs = df.iloc[1, :][0]
        Ts = 1/fs
        df = df.drop([0, 1]).reset_index(drop=True).reset_index()
        df.loc[:, 'time'] = get_sample_time(df['index'], initial_time, Ts)
    else:
        df = df.drop([0, 1]).reset_index(drop=True).reset_index()
        df['time'] = df.apply(lambda x : 
                              (datetime.utcfromtimestamp(x['diff'] + timestamp).strftime("%H:%M:%S:%f")), axis=1)
    return df

In [3]:
path_to_acc = "../data/datos_E4/P1/1/ACC.csv"
path_to_eda = "../data/datos_E4/P1/1/EDA.csv"
path_to_bvp = "../data/datos_E4/P1/1/BVP.csv"
path_to_temp = "../data/datos_E4/P1/1/TEMP.csv"
path_to_hr = "../data/datos_E4/P1/1/HR.csv"
path_to_ibi = "../data/datos_E4/P1/1/IBI.csv"

acc_col_name = ['x', 'y', 'z']
eda_col_name = ['EDA'] 
bvp_col_name = ['BVP']
temp_col_name = ['TEMP']
hr_col_name = ['HR']
ibi_col_name = ['diff', 'IBI']

In [4]:
acc_df = get_dataframe(
     signal='acc',
     file_path=path_to_acc,
     column_names=acc_col_name)

eda_df = get_dataframe(
     signal='eda',
     file_path=path_to_eda,
     column_names=eda_col_name)

bvp_df = get_dataframe(
     signal='bvp',
     file_path=path_to_bvp,
     column_names=bvp_col_name)

temp_df = get_dataframe(
     signal='temp',
     file_path=path_to_temp,
     column_names=temp_col_name)

hr_df = get_dataframe(
     signal='hr',
     file_path=path_to_hr,
     column_names=hr_col_name)
    
    
ibi_df = get_dataframe(
    signal='ibi',
    file_path=path_to_ibi,
    column_names=ibi_col_name)

In [5]:
hr_df.head(-10)

       index     HR             time
0          0  55.00  05:24:54:000000
1          1  55.00  05:24:55:000000
2          2  56.00  05:24:56:000000
3          3  57.75  05:24:57:000000
4          4  63.80  05:24:58:000000
...      ...    ...              ...
58655  58655  99.25  21:42:29:000000
58656  58656  99.00  21:42:30:000000
58657  58657  98.73  21:42:31:000000
58658  58658  98.52  21:42:32:000000
58659  58659  98.40  21:42:33:000000

[58660 rows x 3 columns]

In [6]:
temp_df.head(-10)

         index   TEMP             time
0            0  32.87  05:24:44:000000
1            1  32.87  05:24:44:250000
2            2  32.87  05:24:44:500000
3            3  32.87  05:24:44:750000
4            4  32.87  05:24:45:000000
...        ...    ...              ...
234673  234673  23.91  21:42:32:250000
234674  234674  23.91  21:42:32:500000
234675  234675  23.91  21:42:32:750000
234676  234676  23.91  21:42:33:000000
234677  234677  23.91  21:42:33:250000

[234678 rows x 3 columns]

In [ ]:
fig = go.Figure()

fig.add_trace(go.Scatter(
                x=acc_df['time'][0:960],
                y=acc_df['x'][0:960],
                mode='lines',
                name='X-axis'))
fig.add_trace(go.Scatter(
                x=acc_df['time'][0:960],
                y=acc_df['y'][0:960],
                mode='lines',
                name='Y-axis'))
fig.add_trace(go.Scatter(
                x=acc_df['time'][0:960],
                y=acc_df['z'][0:960],
                mode='lines',
                name='Z-axis'))

fig.update_layout(title='Acc data measured for patien 1')

fig.show()

In [ ]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=temp_df['time'],
    y=temp_df['TEMP'],
    mode='lines',
    name='Temperature'))

fig.update_layout(title='Temperature meassured for patient 1')

fig.show()

In [ ]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=bvp_df['time'],
    y=bvp_df['BVP'],
    mode='lines',
    name='BVP'))

fig.update_layout(title='BVP meassured for patient 1')

fig.show()

In [ ]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=eda_df['index'],
    y=eda_df['EDA'],
    mode='lines',
    name='EDA'))

fig.update_layout(title='EDA meassured for patient 1')

fig.show()

In [ ]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=hr_df['time'][0:960],
    y=hr_df['HR'][0:960],
    mode='lines',
    name='HR'))

fig.update_layout(title='HR meassured for patient 1')

fig.show()

In [ ]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=ibi_df['time'],
    y=ibi_df['IBI'],
    mode='lines',
    name='IBI'))

fig.update_layout(title='IBI meassured for patient 1')

fig.show()

In [ ]:
acc_df.shape

In [ ]:
hr_df.shape